<?php

namespace OC\PlatformBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * AdvertSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkillRepository extends EntityRepository
{
    public function getAdvertSkillsWithNames($advert)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->where('a.advert = :id')
            ->setParameter('id', $advert)
            ->leftJoin('a.skill', 's')
            ->addSelect('s');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
